FROM node:20-bookworm

USER root

ENV DEBIAN_FRONTEND=noninteractive
RUN echo 'Acquire::ForceIPv4 "true";' > /etc/apt/apt.conf.d/99force-ipv4

RUN apt-get update \
  && apt-get install -y --no-install-recommends python3 python3-pip \
  && pip3 install --no-cache-dir pillow piexif exifread \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

RUN npm install -g @n8n/task-runner

CMD ["n8n-task-runner"]
