FROM node:20-bookworm

USER root

# Python + libs
RUN apt-get update && apt-get install -y --no-install-recommends \
  python3 python3-pip \
  libjpeg-dev zlib1g-dev libpng-dev \
  && pip3 install --no-cache-dir pillow piexif exifread \
  && rm -rf /var/lib/apt/lists/*

# offizieller Task Runner
RUN npm install -g @n8n/task-runner

CMD ["n8n-task-runner"]
